language: php

php:
  - 5.4
  - 5.5

branches:
  only:
    - master

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install
  - git config --global user.email "test@travis-ci.org"
  - git config --global user.name "Travis"

script:
  - bin/phpunit --coverage-clover "clover"

after_success:
  - curl -sL https://bit.ly/artifact-uploader | php
  
